In [1]:
'''This file is for the numpy tutorials from Jose in Udemy
'''

'This file is for the numpy tutorials from Jose in Udemy\n'

In [1]:
import numpy as np

In [2]:
# gives 5 numbers from range 0 to 1 
# gives one dimension array
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
np.random.randint(0,10,5)

array([3, 3, 3, 1, 2])

In [4]:
ranarr = np.random.randint(0,100,10)

In [5]:
ranarr

array([13, 61, 99, 97, 14, 47, 98, 54, 68, 16])

In [6]:
ranarr.max()


99

In [7]:
ranarr.min()

13

In [8]:
ranarr.argmax() # position  of max value in the array

2

Array indexing


In [9]:
arr = np.arange(0,10)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
slice_arr = arr[:5]

In [12]:
slice_arr

array([0, 1, 2, 3, 4])

In [13]:
slice_arr[:] = 100

In [14]:
slice_arr

array([100, 100, 100, 100, 100])

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [16]:
copy_arr = arr.copy()

In [17]:
copy_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [18]:
copy_arr[5:7] = 99

In [19]:
copy_arr

array([100, 100, 100, 100, 100,  99,  99,   7,   8,   9])

In [20]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [21]:
arr = np.arange(0,10)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr_2d = np.array([[5,10,15],[20,25,30], [35,40,45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [26]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [27]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [28]:
arr_2d[1,:]

array([20, 25, 30])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.arange(1,11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
greater_than_5 = arr > 5

In [34]:
arr[greater_than_5]

array([ 6,  7,  8,  9, 10])

In [35]:
div_two = arr % 2 == 0

In [36]:
print(arr % 2 == 0)

[False  True False  True False  True False  True False  True]


In [37]:
arr[div_two]

array([ 2,  4,  6,  8, 10])

In [38]:
arr2d = np.arange(1,51).reshape(5,10)

In [39]:
arr2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [40]:
arr2d[2:5,4:7]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [41]:
arr2d[3:,2:4]

array([[33, 34],
       [43, 44]])

In [42]:
np.random.rand(10)

array([0.46487172, 0.08158571, 0.73003381, 0.2641276 , 0.49411625,
       0.29957859, 0.8222543 , 0.54541974, 0.7233692 , 0.22299713])

In [43]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])